# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-07 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('announcements', '0006_convert_textfield_to_richtextfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='site',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
