# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-07 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_siterelated_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date_start'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
    ]
