name: Release to PyPI

# Only fire on new tags that match semver
on:
  create:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  # Upload the release to PyPI
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Build package
        run: |
          python -m pip install --upgrade pip wheel twine
          python setup.py sdist bdist_wheel
          twine check dist/*
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
