name: Test and lint | Bump version

# Fires on all incoming commits
on: [push]

jobs:

  # Test and lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run tests
        run: tox

  # Bump version, generate changelog, and push tags
  bump:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Generate changelog and tag
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          npx standard-version --dry-run
      # - name: Push changelog and tag
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     tags: true
